name: plankassembly
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.3.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cudatoolkit=11.3.1
  - curl=7.87.0
  - double-conversion=3.2.0
  - eigen=3.4.0
  - expat=2.5.0
  - ffmpeg=4.4.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeimage=3.18.0
  - freetype=2.10.4
  - gl2ps=1.4.2
  - gmp=6.2.1
  - gnutls=3.6.13
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=72.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - jsoncpp=1.9.5
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libcurl=7.87.0
  - libdeflate=1.10
  - libdrm=2.4.114
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.2.1
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libogg=1.3.4
  - libpciaccess=0.17
  - libpng=1.6.37
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libtheora=1.1.1
  - libtiff=4.3.0
  - libuuid=2.38.1
  - libuv=1.43.0
  - libva=2.19.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.10.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - lightning-utilities=0.9.0
  - llvm-openmp=16.0.6
  - loguru=0.7.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.6
  - numpy=1.24.3
  - numpy-base=1.24.3
  - occt=7.6.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1v
  - packaging=23.1
  - pillow=8.2.0
  - pip=23.2.1
  - proj=9.0.0
  - pthread-stubs=0.4
  - pugixml=1.11.4
  - python=3.8.0
  - python_abi=3.8
  - pythonocc-core=7.6.2
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - rapidjson=1.1.0
  - readline=8.2
  - six=1.16.0
  - sqlite=3.42.0
  - svgwrite=1.4.3
  - svt-av1=1.1.0
  - tbb=2021.9.0
  - tbb-devel=2021.9.0
  - tk=8.6.12
  - torchaudio=0.10.0
  - torchvision=0.11.0
  - typing_extensions=4.7.1
  - utfcpp=3.2.4
  - vtk=9.1.0
  - wheel=0.38.4
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxt=1.3.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - asttokens==2.2.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backcall==0.2.0
    - black==21.4b2
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.6
    - cloudpickle==2.2.1
    - commonmark==0.9.1
    - contourpy==1.1.0
    - cycler==0.11.0
    - decorator==5.1.1
    - https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/detectron2-0.6%2Bcu113-cp38-cp38-linux_x86_64.whl
    - docstring-parser==0.15
    - executing==1.2.0
    - fonttools==4.42.0
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - future==0.18.3
    - fvcore==0.1.5.post20221221
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.57.0
    - hydra-core==1.3.2
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.1
    - iopath==0.1.9
    - ipython==8.12.2
    - jedi==0.19.0
    - jsonargparse==4.23.1
    - kiwisolver==1.4.4
    - markdown==3.4.4
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - parso==0.8.3
    - pathspec==0.11.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - portalocker==2.7.0
    - prompt-toolkit==3.0.39
    - protobuf==4.24.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycocotools==2.0.6
    - pydeprecate==0.3.2
    - pydot==1.4.2
    - pygments==2.16.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytorch-lightning==1.7.7
    - pyyaml==6.0.1
    - regex==2023.8.8
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rich==12.5.1
    - rsa==4.9
    - scipy==1.10.1
    - setuptools==59.5.0
    - shapely==2.0.1
    - stack-data==0.6.2
    - svgpathtools==1.6.1
    - tabulate==0.9.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.1
    - termcolor==2.3.0
    - toml==0.10.2
    - torchmetrics==0.11.4
    - tqdm==4.66.1
    - traitlets==5.9.0
    - trimesh==3.23.1
    - typeshed-client==2.3.0
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - werkzeug==2.3.6
    - yacs==0.1.8
    - yarl==1.9.2
    - zipp==3.16.2
